replication.policy.class=org.apache.kafka.connect.mirror.IdentityReplicationPolicy

clusters = edge, central

edge.bootstrap.servers = kafka-edge:9092
central.bootstrap.servers = kafka-central:9092

edge->central.enabled = true
central->edge.enabled = false

edge->central.topics = test-events

replication.factor = 1
offset-syncs.topic.replication.factor = 1
checkpoints.topic.replication.factor = 1
heartbeats.topic.replication.factor = 1

config.storage.replication.factor = 1
offset.storage.replication.factor = 1
status.storage.replication.factor = 1